name: frontend
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.4.4
  dio: ^5.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo_crop.png
    - assets/bomb.json
    - assets/cat.json
    - assets/duck.json
    - assets/panda.json
    - assets/potato.json